### ISSUE TITLE
migrations prefix w/ rework?

### ISSUE THREAD

**Issue by chadfurman** [chadfurman/rpg-boilerplate#11]
@benjie when you re-work a migration in sqitch, it keeps its original name and yet gets added to the end of the sqitch.plan  -- I'm not convinced that the numeric prefix on the migrations is appropriate.

Prefixing the migrations with their type allows cleaner organization of the deploy folder.  Inside the migrations there are also dependencies (albeit not all of them) outlined at the top of the files.

The exact order of the existing migrations is less important to someone wanting to make changes than having the files grouped nicely by their type (and also easily re-workable)

I'm going to change the migrations back, unless you have a compelling reason why they should be prefixed?

**Comment by benjie** [comment]
Nope; I don't use sqitch so I was just commenting as a newcomer that I wasn't sure which order to look at them as. What happens if you rewrite a function a few times in different migrations?

**Comment by chadfurman** [comment]
Everytime you re-work a function, you have to have a tag.  If you're on a branch and working on it, then you just revert / deploy and modify it in place.  If you've already deployed it, then that release was tagged.  If you need to make a modification then you rework.  

When you rework, it takes the current version, copies it and agives it a tag suffix, then makes the current revert script a copy of the now-old deploy script, and then you can modify the deploy script in place.  So function_currentProfile always references the latest version, and there are old versions with tag suffixes auto-added to sqitch.plan which can be ignored.

**Comment by chadfurman** [comment]
I've reverted the previous migration prefixing, as I don't like it :)
