### ISSUE TITLE
How can I connect to the DB Docker port?

### ISSUE THREAD

**Issue by Antibioticvz** [chadfurman/rpg-boilerplate#17]
I know that we can do `cd db && docker exec -it 742ea7492eb1 /bin/sh` but how for example we can connect IDE? 

> [08001] Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

> 742ea7492eb1        rpgboilerplate_db         "docker-entrypoint.s…"   4 minutes ago       Up 4 minutes        0.0.0.0:8001->5432/tcp          rpgboilerplate_db_1

> ports:
>       - '8001:5432'

<img width="723" alt="screen shot 2018-02-09 at 8 01 56 pm" src="https://user-images.githubusercontent.com/6497819/36057465-1c86dd0e-0dd4-11e8-9a82-6cd04a5da201.png">

**Comment by benjie** [comment]
I don’t use docker, but my guess is 8001:5432 means map port 8001 outside the container to port 5432 inside the container, so outside the container you should attempt to connect to port 8001.

**Comment by Antibioticvz** [comment]
You are right.
