### ISSUE TITLE
How to use multiple schemas?

### ISSUE THREAD

**Issue by Antibioticvz** [chadfurman/rpg-boilerplate#18]
I've inserted a couple of tables to the public and want to use it in the api.
Related to [this](https://github.com/postgraphql/postgraphql/blob/abd7c388f32a1f499258f6c0af5668bfa5793a7d/docs/library.md#createpostgraphqlschemapgconfig-schemaname--public-options-promisegraphqlschema) It sould be possible as simple as 

> May be an array for multiple schemas.

`app.use(postgraphile(pgConnectionString, [pgSchemas, pgSchemasPublic], pgOptions))` but it does not work for me.
How can I use the public schema in this case?
`import express from 'express'
import postgraphile from 'postgraphile'

const app = express()
const pgConnectionString = process.env.DB_URI
const pgSchemas = process.env.POSTGRAPHILE_SCHEMAS.split(',')
const pgSchemasGramm = process.env.POSTGRAPHILE_SCHEMAS_PUBLIC.split(',')
const pgOptions = JSON.parse(process.env.POSTGRAPHILE_OPTIONS)

app.use(postgraphile(pgConnectionString, [pgSchemas, pgSchemasPublic], pgOptions))

app.listen(3000, '0.0.0.0', function () {
  console.info('NODE_ENV: ' + process.env.NODE_ENV)
  console.info('Postgraphile API started.\n')
})`

**Comment by benjie** [comment]
`[pgSchemas, pgSchemasPublic]` is an array of arrays - effectively `[['schema1', 'schema2'], ['schema3', 'schema4']]` - you want just a single level deep array `['schema1', 'schema2', 'schema3', 'schema4']` which you can achieve via: `[...pgSchemas, ...pgSchemasPublic]` (assuming a recent Node.js).

**Comment by Antibioticvz** [comment]
Sorry, I'm pretty new at this stack. What I need to do to re-generate the API and schema.gql?

**Comment by Antibioticvz** [comment]
I need to make a tutorial "How to start" when I finished. Thank you

**Comment by chadfurman** [comment]
Great question!  :)
